POST http://localhost:3000/process-video
Content-Type: application/json

{
  "inputFilePath": "/home/vinicius/Downloads/example-epic-of-gilgamesh.mp4",
  "outputFilePath": "/home/vinicius/Downloads/360p-example-epic-of-gilgamesh.mp4"
}